version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: grocery_store
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "--password=password"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    container_name: grocery_app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://admin:password@mysql:3306/grocery_store
    volumes:
      - .:/app
    command: python database/create_tables.py

volumes:
  mysql_data:
